import PptxGenJS from "pptxgenjs";
import type {
  CuratorOutput,
  PlannerOutput,
  InfographicOutput,
  PlanningContent,
  SlideMeta,
  Infographic,
} from "@/components/StudioJobResult";

export type PptxExportInput = {
  topic: string;
  level?: string;
  curator: CuratorOutput;
  planner: PlannerOutput;
  planning?: PlanningContent;
  infographics?: InfographicOutput;
};

// ─── KEG 브랜드 토큰 ─────────────────────────────────
const COLORS = {
  primary: "0B1437", // 짙은 네이비 (KEG 메인)
  primaryLight: "1E293B",
  accent: "F59E0B", // 따뜻한 앰버 (교육·지혜)
  accentLight: "FCD34D",
  bgLight: "FAFAF9",
  bgWhite: "FFFFFF",
  textDark: "18181B",
  textMuted: "71717A",
  textOnDark: "F4F4F5",
  border: "E4E4E7",
  divider: "27272A",
} as const;

const FONT = {
  korean: "맑은 고딕",
  englishMono: "Consolas",
} as const;

/**
 * Studio 콘텐츠 → 디자인된 .pptx 파일.
 * KEG 브랜드 톤 (네이비 + 앰버) · 16:9 widescreen · 맑은 고딕.
 *
 * 슬라이드 구성:
 *   1. 표지 (다크 배경, 큰 타이포)
 *   2. 학습 목표 (앰버 강조)
 *   3. 챕터 개요 (목차)
 *   4..N+3. 본문 슬라이드 (인포그래픽 시각화 포함)
 *   N+4. 정리 (학습 목표 재확인)
 */
export async function generatePptx(input: PptxExportInput): Promise<Buffer> {
  const pptx = new PptxGenJS();

  pptx.title = input.topic;
  pptx.author = "KEG AI Studio";
  pptx.company = "KEG · Aurein Studio";
  pptx.subject = input.curator.chapter_title;
  pptx.layout = "LAYOUT_WIDE";

  defineMasters(pptx, input);

  const infMap = new Map<number, Infographic>(
    (input.infographics?.infographics ?? []).map((i) => [i.slide_number, i]),
  );

  addCoverSlide(pptx, input);
  addObjectivesSlide(pptx, input);
  if (input.planning?.outline?.chapter_outline?.length) {
    addOutlineSlide(pptx, input);
  }
  for (const slide of input.planner.slides) {
    addContentSlide(pptx, slide, infMap.get(slide.slide_number));
  }
  addClosingSlide(pptx, input);

  const buf = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  return buf;
}

// ─── 마스터 슬라이드 정의 ──────────────────────────────
function defineMasters(pptx: PptxGenJS, _input: PptxExportInput) {
  // 다크 표지용
  pptx.defineSlideMaster({
    title: "MASTER_COVER",
    background: { color: COLORS.primary },
    objects: [
      // 좌상단 앰버 강조 바
      {
        rect: { x: 0.5, y: 0.5, w: 0.6, h: 0.08, fill: { color: COLORS.accent } },
      },
      // 좌상단 브랜드
      {
        text: {
          text: "KEG · AI STUDIO",
          options: {
            x: 0.5,
            y: 0.7,
            w: 6,
            h: 0.3,
            fontSize: 11,
            color: COLORS.accent,
            fontFace: FONT.korean,
            bold: true,
            charSpacing: 4,
          },
        },
      },
      // 우하단 발자국
      {
        text: {
          text: "Generated by 13 AI agents · KEG",
          options: {
            x: 7,
            y: 7.1,
            w: 6.1,
            h: 0.3,
            fontSize: 9,
            color: COLORS.accent,
            fontFace: FONT.korean,
            align: "right",
            italic: true,
          },
        },
      },
    ],
  });

  // 본문용 (밝은 배경)
  pptx.defineSlideMaster({
    title: "MASTER_CONTENT",
    background: { color: COLORS.bgLight },
    objects: [
      // 우상단 네이비 강조 바
      {
        rect: { x: 12.6, y: 0, w: 0.73, h: 0.4, fill: { color: COLORS.primary } },
      },
      // 좌상단 KEG 워드마크
      {
        text: {
          text: "KEG",
          options: {
            x: 0.5,
            y: 0.15,
            w: 1.5,
            h: 0.3,
            fontSize: 12,
            color: COLORS.primary,
            fontFace: FONT.korean,
            bold: true,
            charSpacing: 6,
          },
        },
      },
      // 하단 구분선
      {
        line: {
          x: 0.5,
          y: 7.0,
          w: 12.33,
          h: 0,
          line: { color: COLORS.border, width: 0.5 },
        },
      },
      // 하단 푸터
      {
        text: {
          text: "AI Studio · 본 자료는 AI가 생성한 베타 콘텐츠입니다",
          options: {
            x: 0.5,
            y: 7.1,
            w: 12.33,
            h: 0.3,
            fontSize: 9,
            color: COLORS.textMuted,
            fontFace: FONT.korean,
            align: "left",
          },
        },
      },
    ],
  });
}

// ─── 표지 슬라이드 ────────────────────────────────────
function addCoverSlide(pptx: PptxGenJS, input: PptxExportInput) {
  const s = pptx.addSlide({ masterName: "MASTER_COVER" });

  // 카테고리 라벨 (작게)
  s.addText(`EDUCATION · ${levelLabel(input.level ?? "")}`, {
    x: 0.5,
    y: 2.2,
    w: 12.3,
    h: 0.3,
    fontSize: 12,
    color: COLORS.accent,
    fontFace: FONT.korean,
    bold: true,
    charSpacing: 8,
  });

  // 주제 (큰 타이포)
  s.addText(input.topic, {
    x: 0.5,
    y: 2.8,
    w: 12.3,
    h: 1.6,
    fontSize: 48,
    bold: true,
    color: COLORS.textOnDark,
    fontFace: FONT.korean,
    valign: "top",
    lineSpacingMultiple: 1.15,
  });

  // 챕터 제목 (서브타이틀)
  s.addText(input.curator.chapter_title, {
    x: 0.5,
    y: 4.6,
    w: 12.3,
    h: 0.6,
    fontSize: 22,
    color: COLORS.accentLight,
    fontFace: FONT.korean,
    italic: false,
  });

  // 구분선
  s.addShape("line", {
    x: 0.5,
    y: 5.5,
    w: 2,
    h: 0,
    line: { color: COLORS.accent, width: 2 },
  });

  // 학습 목표 미리보기 (3개)
  s.addText(
    input.curator.learning_objectives.slice(0, 3).map((obj, i) => ({
      text: `${i + 1}.  ${obj}`,
      options: { breakLine: true },
    })),
    {
      x: 0.5,
      y: 5.8,
      w: 12.3,
      h: 1.1,
      fontSize: 13,
      color: COLORS.textOnDark,
      fontFace: FONT.korean,
      lineSpacingMultiple: 1.3,
    },
  );

  s.addNotes(
    `주제: ${input.topic}\n수준: ${levelLabel(input.level ?? "")}\n\n학습 목표:\n` +
      input.curator.learning_objectives.map((o, i) => `  ${i + 1}. ${o}`).join("\n"),
  );
}

// ─── 학습 목표 슬라이드 ───────────────────────────────
function addObjectivesSlide(pptx: PptxGenJS, input: PptxExportInput) {
  const s = pptx.addSlide({ masterName: "MASTER_CONTENT" });

  // 섹션 라벨
  s.addText("01 · LEARNING OBJECTIVES", {
    x: 0.5,
    y: 0.7,
    w: 12.3,
    h: 0.3,
    fontSize: 11,
    color: COLORS.accent,
    fontFace: FONT.korean,
    bold: true,
    charSpacing: 6,
  });

  // 제목
  s.addText("학습 목표", {
    x: 0.5,
    y: 1.05,
    w: 12.3,
    h: 0.8,
    fontSize: 36,
    bold: true,
    color: COLORS.primary,
    fontFace: FONT.korean,
  });

  // 강조 바
  s.addShape("rect", {
    x: 0.5,
    y: 1.95,
    w: 0.8,
    h: 0.08,
    fill: { color: COLORS.accent },
    line: { color: COLORS.accent, width: 0 },
  });

  // 학습 목표 — 큰 카드 스타일
  const objCount = input.curator.learning_objectives.length;
  input.curator.learning_objectives.forEach((obj, i) => {
    const y = 2.4 + i * 1.3;
    const maxY = 6.5;
    if (y > maxY) return;

    // 번호 동그라미
    s.addText(String(i + 1), {
      x: 0.5,
      y,
      w: 0.7,
      h: 0.7,
      fontSize: 22,
      bold: true,
      color: COLORS.accent,
      fontFace: FONT.korean,
      align: "center",
      valign: "middle",
    });

    // 본문
    s.addText(obj, {
      x: 1.3,
      y,
      w: 11.5,
      h: 0.8,
      fontSize: 18,
      color: COLORS.textDark,
      fontFace: FONT.korean,
      valign: "middle",
      lineSpacingMultiple: 1.3,
    });
  });

  s.addNotes(`총 ${objCount}개 학습 목표`);
}

// ─── 챕터 개요 슬라이드 ───────────────────────────────
function addOutlineSlide(pptx: PptxGenJS, input: PptxExportInput) {
  const s = pptx.addSlide({ masterName: "MASTER_CONTENT" });
  const chapters = input.planning!.outline.chapter_outline;

  s.addText("02 · COURSE OUTLINE", {
    x: 0.5,
    y: 0.7,
    w: 12.3,
    h: 0.3,
    fontSize: 11,
    color: COLORS.accent,
    fontFace: FONT.korean,
    bold: true,
    charSpacing: 6,
  });
  s.addText("강의 개요", {
    x: 0.5,
    y: 1.05,
    w: 12.3,
    h: 0.8,
    fontSize: 36,
    bold: true,
    color: COLORS.primary,
    fontFace: FONT.korean,
  });
  s.addShape("rect", {
    x: 0.5,
    y: 1.95,
    w: 0.8,
    h: 0.08,
    fill: { color: COLORS.accent },
    line: { color: COLORS.accent, width: 0 },
  });

  // 챕터 테이블
  const rows: PptxGenJS.TableRow[] = [
    [
      { text: "#", options: { bold: true, color: COLORS.textOnDark, fill: { color: COLORS.primary }, align: "center" as const, fontFace: FONT.korean } },
      { text: "챕터 제목", options: { bold: true, color: COLORS.textOnDark, fill: { color: COLORS.primary }, fontFace: FONT.korean } },
      { text: "섹션", options: { bold: true, color: COLORS.textOnDark, fill: { color: COLORS.primary }, align: "center" as const, fontFace: FONT.korean } },
      { text: "분", options: { bold: true, color: COLORS.textOnDark, fill: { color: COLORS.primary }, align: "right" as const, fontFace: FONT.korean } },
    ],
    ...chapters.slice(0, 8).map<PptxGenJS.TableRow>((ch) => [
      { text: String(ch.chapter_number), options: { color: COLORS.accent, align: "center" as const, fontFace: FONT.korean, bold: true } },
      { text: ch.title, options: { color: COLORS.textDark, fontFace: FONT.korean } },
      { text: String(ch.sections.length), options: { color: COLORS.textMuted, align: "center" as const, fontFace: FONT.korean } },
      { text: String(ch.duration_minutes), options: { color: COLORS.textMuted, align: "right" as const, fontFace: FONT.korean } },
    ]),
  ];

  s.addTable(rows, {
    x: 0.5,
    y: 2.4,
    w: 12.33,
    colW: [0.8, 8.5, 1.3, 1.73],
    rowH: 0.4,
    fontSize: 13,
    border: { type: "solid", pt: 0.5, color: COLORS.border },
  });

  s.addText(`총 ${input.planning!.outline.total_duration_minutes}분 · ${chapters.length}챕터`, {
    x: 0.5,
    y: 6.5,
    w: 12.3,
    h: 0.4,
    fontSize: 12,
    color: COLORS.textMuted,
    fontFace: FONT.korean,
    italic: true,
  });

  s.addNotes(
    `논리적 흐름: ${input.planning!.outline.logical_flow_rationale}`,
  );
}

// ─── 본문 슬라이드 (인포그래픽 시각화 포함) ─────────────
function addContentSlide(
  pptx: PptxGenJS,
  slide: SlideMeta,
  infographic: Infographic | undefined,
) {
  const s = pptx.addSlide({ masterName: "MASTER_CONTENT" });
  const hasInfographic = infographic && infographic.type !== "none";

  // 슬라이드 번호 라벨
  s.addText(`SLIDE ${String(slide.slide_number).padStart(2, "0")}`, {
    x: 0.5,
    y: 0.7,
    w: 6,
    h: 0.3,
    fontSize: 11,
    color: COLORS.accent,
    fontFace: FONT.korean,
    bold: true,
    charSpacing: 6,
  });

  // 제목
  s.addText(slide.title, {
    x: 0.5,
    y: 1.05,
    w: 12.3,
    h: 0.9,
    fontSize: 32,
    bold: true,
    color: COLORS.primary,
    fontFace: FONT.korean,
    valign: "top",
  });

  // 강조 바
  s.addShape("rect", {
    x: 0.5,
    y: 2.0,
    w: 0.8,
    h: 0.08,
    fill: { color: COLORS.accent },
    line: { color: COLORS.accent, width: 0 },
  });

  // 본문 영역 — 인포그래픽 있으면 좌측 절반, 없으면 전체
  const bodyW = hasInfographic ? 6.5 : 12.3;
  s.addText(
    slide.content_blocks.map((block) => ({
      text: block,
      options: {
        bullet: { type: "bullet", code: "25A0" }, // ▪ 사각형
        breakLine: true,
        color: COLORS.textDark,
      },
    })),
    {
      x: 0.5,
      y: 2.5,
      w: bodyW,
      h: 4,
      fontSize: 17,
      fontFace: FONT.korean,
      lineSpacingMultiple: 1.4,
      paraSpaceAfter: 8,
    },
  );

  // 인포그래픽 패널 (우측)
  if (hasInfographic) {
    drawInfographicPanel(s, infographic);
  }

  // 시각 제안 (하단 hint)
  if (slide.visual_suggestions && !hasInfographic) {
    s.addText(`💡 ${slide.visual_suggestions}`, {
      x: 0.5,
      y: 6.55,
      w: 12.3,
      h: 0.4,
      fontSize: 11,
      italic: true,
      color: COLORS.textMuted,
      fontFace: FONT.korean,
    });
  }

  // 발표자 노트 + 인포그래픽 명세 (노트 영역)
  const noteParts: string[] = [
    `[발표자 노트]`,
    slide.speaker_notes,
    "",
    `[시각 제안]`,
    slide.visual_suggestions,
  ];
  if (hasInfographic) {
    noteParts.push(
      "",
      `[인포그래픽 (${infographic.type})]`,
      `제목: ${infographic.title}`,
      `레이아웃: ${infographic.layout_description}`,
      `요소: ${infographic.elements.join(", ")}`,
      `강조 색상: ${infographic.color_emphasis.join(", ")}`,
    );
  }
  s.addNotes(noteParts.join("\n"));
}

// ─── 인포그래픽 패널 (슬라이드 우측에 시각화) ──────────
function drawInfographicPanel(s: PptxGenJS.Slide, inf: Infographic) {
  // 우측 패널 배경 (연한 네이비 박스)
  s.addShape("rect", {
    x: 7.3,
    y: 2.5,
    w: 5.5,
    h: 4,
    fill: { color: "F1F5F9" },
    line: { color: COLORS.border, width: 0.5 },
  });

  // 타입 배지
  s.addText(inf.type.toUpperCase(), {
    x: 7.5,
    y: 2.7,
    w: 1.5,
    h: 0.3,
    fontSize: 9,
    color: COLORS.bgWhite,
    fontFace: FONT.korean,
    bold: true,
    fill: { color: COLORS.primary },
    align: "center",
    charSpacing: 4,
  });

  // 인포그래픽 제목
  s.addText(inf.title, {
    x: 7.5,
    y: 3.15,
    w: 5.1,
    h: 0.7,
    fontSize: 15,
    bold: true,
    color: COLORS.primary,
    fontFace: FONT.korean,
  });

  // 요소 목록 (각각 박스로 시각화)
  const elementsToShow = inf.elements.slice(0, 5); // 최대 5개
  const startY = 3.95;
  const itemH = 0.45;
  elementsToShow.forEach((el, i) => {
    const y = startY + i * itemH;
    // 좌측 도트
    s.addShape("ellipse", {
      x: 7.55,
      y: y + 0.08,
      w: 0.2,
      h: 0.2,
      fill: { color: COLORS.accent },
      line: { color: COLORS.accent, width: 0 },
    });
    // 텍스트
    s.addText(el, {
      x: 7.85,
      y: y,
      w: 4.85,
      h: itemH,
      fontSize: 12,
      color: COLORS.textDark,
      fontFace: FONT.korean,
      valign: "middle",
    });
  });

  // 레이아웃 설명 (하단 italic)
  s.addText(inf.layout_description, {
    x: 7.5,
    y: 6.15,
    w: 5.1,
    h: 0.3,
    fontSize: 9,
    italic: true,
    color: COLORS.textMuted,
    fontFace: FONT.korean,
  });
}

// ─── 정리 슬라이드 ────────────────────────────────────
function addClosingSlide(pptx: PptxGenJS, input: PptxExportInput) {
  const s = pptx.addSlide({ masterName: "MASTER_COVER" });

  // 작은 라벨
  s.addText("FIN · 정리", {
    x: 0.5,
    y: 2.5,
    w: 12.3,
    h: 0.3,
    fontSize: 12,
    color: COLORS.accent,
    fontFace: FONT.korean,
    bold: true,
    charSpacing: 8,
  });

  // 큰 메시지
  s.addText("오늘 학습한 내용", {
    x: 0.5,
    y: 3,
    w: 12.3,
    h: 1.2,
    fontSize: 44,
    bold: true,
    color: COLORS.textOnDark,
    fontFace: FONT.korean,
  });

  // 학습 목표 체크
  s.addText(
    input.curator.learning_objectives.map((obj) => ({
      text: `✓   ${obj}`,
      options: { breakLine: true, color: COLORS.textOnDark },
    })),
    {
      x: 0.5,
      y: 4.6,
      w: 12.3,
      h: 1.8,
      fontSize: 16,
      fontFace: FONT.korean,
      lineSpacingMultiple: 1.5,
    },
  );

  // 끝 메시지
  s.addText(`수고하셨습니다 · ${input.topic}`, {
    x: 0.5,
    y: 6.6,
    w: 12.3,
    h: 0.4,
    fontSize: 12,
    color: COLORS.accent,
    fontFace: FONT.korean,
    italic: true,
  });
}

function levelLabel(level: string): string {
  return level === "beginner"
    ? "초급"
    : level === "intermediate"
      ? "중급"
      : level === "advanced"
        ? "고급"
        : level;
}
